### PR TITLE
Michael/dish bug fixes

### LINKED ISSUE #126: Dish and Donation Dish Bug
### Problem Description 
Currently there are some bugs and logic errors regarding our rendering of the list of dishes in our donation cart. Right now, the screen to render our list of dishes in our donation cart are `DonationDishes` objects but since those objects don't give us the full data of the dish like name, price, etc, the donation acrt list screens are not rendering properly. 

If you navigate to the Donate tab, click on the shopping cart you'll be directed to the DonateListScreen which is being rendered at `/screens/DonationForm/DonationList`. When you go back and start adding items to the cart, you'll notice a couple of bugs like missing key attribute on children and the DonateListScreen  rendering the ids of the dishes rather than their names. 

### Task at Hand
Your task is to solve these problems as well as add some features. 
1. Since our donationCart only stores `DonationDish` objects but we need to get other dish attributes like name, etc from the `Dish` object, how can we properly render the DonateListScreen while passing in the right objects to the `<DonateQuantityModal />, <Row />` and updating the donationCart state properly when a user deletes a `DonationDish` or changes its quantity? 

2. The two buttons at the button of the DonateListScreen are just Views, make them actually buttons using <TouchableHighlight /> or using the button components Patrick made at `/components/Button`. 
     * When Add Dish to Donate is clicked, go back to the Donate Tab home screen 
     * When Schedule pickup is clicked, navigate to the AddressScreen on the DonorStack

3. In the 3 dot options rendered in each row, if the user chooses view dish, pass the Dish object to the DishProfile screen and render that screen. You'll need to modify the DishProfile screen to take in a custom dish object in its props as well as conditionally render the quantity and add to donation list button at the button. In other words, we just want to return a view of the dish, ignoring the change quantity functionality that is also rendering. 

For reference, this ticket is a continuation of this user flow in [figma](https://www.figma.com/file/p70bLCwileiHQoITFpLpLM/Umi-Feeds-%2F-Fall21?node-id=571%3A7597). The stylings are completed by the logic is missing here. 

**Important Notes**
* Please make sure you understand the problem and the code in `/screens/DonationForm/DonationList` first given in task 1 before attempting to code it. It can be a bit confusing since you're jumping right in so please ask 

* Try to find the best solution you can to task 1

### When you're done this is what the app should look like/do:
When a user adds dishes to cart, when they click on the shopping cart, they should see a list of all their dishes with the ability to view them in more details, change their quantity or remove them from the cart. 

### Hints 
* Good luck! 

### Resources 
* Check out hints!

### PR DESCRIPTION
**Pull request by XenonMolecule**
## Dish Bug Fixes

Makes sure that the DonationList Screen is using the expected versions of dishes either DonationDish or Dish.  Also adds functionality to buttons on DonationList Screen and properly links View Donation to show the information about the correct donation that you requested information about.

### How to Test

Add a few items to the cart and look at the cart screen.  You'll see the correct names.  Adding and removing to the list works.  Changing quantity works.  Clicking to view the donation will let you see that donation item's details.  The button at the bottom properly links to the corresponding views.

### Important Changes

- Added a Mapping from ID to Dish in the DonationList Screen as a part of the state of the screen.  This map updates if the length of the user's dishes changes at all when a dish is requested.  I considered if this could introduce a bug if something were added and something else removed from the user's dishes between calls, so I also added a check if the retrieved dish was undefined to try to update the mapping.

### Related Github Issues

- resolves https://github.com/GTBitsOfGood/umi-feeds-app/issues/126

### Related PRs

- NA

### Checklist

- [ ]  Database schema docs have been updated or are not necessary
- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Tests have been written and executed or are not necessary
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (Senior Dev/EM/Designers) have been assigned to this PR

### CODE REVIEW

File: screens/Dishes/DishProfileScreen/index.tsx [hunk 1]
```diff
@@ -67,7 +55,7 @@ export default function DishProfileScreen() {
       </View>
       <View style={styles.imgContainer}>
         <ImageBackground
-          source={{ uri: MockDish.imageLink }}
+          source={{ uri: route.params.dish.imageLink }}
```
Comment (izou3) [inline screens/Dishes/DishProfileScreen/index.tsx]: Consider the case if imageLink is an empty string
